// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldNiyaYdrjuLsUoJIzub3NHJ7tgP05e0',
    appId: '1:729261626521:android:7b9cf52d248697d1131408',
    messagingSenderId: '729261626521',
    projectId: 'floor-measure-cc35e',
    storageBucket: 'floor-measure-cc35e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH2OIzalJVkjGVWYppJ6oyX6UlLlMnEvU',
    appId: '1:729261626521:ios:37f4b4ea98593621131408',
    messagingSenderId: '729261626521',
    projectId: 'floor-measure-cc35e',
    storageBucket: 'floor-measure-cc35e.firebasestorage.app',
    iosBundleId: 'com.dublinproptech.floorMeasure',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI38HtArr-Wm8wzdS32IN7HWqp4ThEp_Y',
    appId: '1:729261626521:web:c5857aebfe56d7a8131408',
    messagingSenderId: '729261626521',
    projectId: 'floor-measure-cc35e',
    authDomain: 'floor-measure-cc35e.firebaseapp.com',
    storageBucket: 'floor-measure-cc35e.firebasestorage.app',
    measurementId: 'G-HPY4PB4LTK',
  );
}
